### ISSUE TITLE
weex run android 总是network error

### ISSUE THREAD

**Issue by uneverno** [zhaokuohaha/weex_android_demo#1]
感谢分享，按照你更改后的内容 仍然是network error，我需要更改什么设置吗？

**Comment by zhaokuohaha** [comment]
您好是生成安卓应用后， 应用打开network error么， 如果是的话， 可能是我服务器那边挂掉了。 应用打开会默认请求 [http://zhiliao.weex.zhaokuo.cc/app.weex.js](http://zhiliao.weex.zhaokuo.cc/app.weex.js)这个文件, 你看看能不能访问到这个地址. 如果需要自己修改`weex.js`文件的路径的话 在`android.config.json`文件里边

**Comment by uneverno** [comment]
我改了其他的入口文件 一直转圈圈了




发自网易邮箱大师
在2017年06月29日 22:09，zhaokuohaha 写道：

您好是生成安卓应用后， 应用打开network error么， 如果是的话， 可能是我服务器那边挂掉了。 应用打开会默认请求 http://zhiliao.weex.zhaokuo.cc/app.weex.js这个文件, 你看看能不能访问到这个地址. 如果需要自己修改weex.js文件的路径的话 在android.config.json文件里边

**Comment by uneverno** [comment]
你好 我终于运行起来了 但是我发现好多vue语法在android studio里面报错 请问这些你是手动修改的？


发自网易邮箱大师
在2017年06月29日 22:18，uneverno 写道：
我改了其他的入口文件 一直转圈圈了




发自网易邮箱大师
在2017年06月29日 22:09，zhaokuohaha 写道：

您好是生成安卓应用后， 应用打开network error么， 如果是的话， 可能是我服务器那边挂掉了。 应用打开会默认请求 http://zhiliao.weex.zhaokuo.cc/app.weex.js这个文件, 你看看能不能访问到这个地址. 如果需要自己修改weex.js文件的路径的话 在android.config.json文件里边

**Comment by zhaokuohaha** [comment]
我是用vscode开发的， 基本没有涉及Android的开发， 前端开发调试之后, 执行weex build andrioid 就可以发布安装包了

**Comment by zhaokuohaha** [comment]
哎呀我收到邮件和短信的通知了
